1. Importing numpy

In [1]:
import numpy as np 

2. THE BASICS

In [24]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get Dimension
a.ndim

1

In [14]:
# Get Shape
b.shape

(2, 3)

In [19]:
# Get Type
data_type = a.dtype
print(data_type)

int16


In [25]:
# Get Size (in bytes)
a.itemsize

4

In [28]:
# Get total size (bytes)
a.nbytes

12




3. Accessing/Changing specific elements, rows, columns, etc

In [32]:
a = np.array([[1,2,3,4,5,6,7,],[8,9,10,11,12,13,14]])
print(a)
a.shape

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

In [33]:
# Get specific element [r, c] (both start with 0)
a[1, 5]

13

In [34]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [36]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [39]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [41]:
# 3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [44]:
# replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]






4. Initializing different types of arrays

In [52]:
# ALL 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [54]:
# ALL 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [56]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [58]:
# Any other number (full_like)
np.full_like((a), 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [60]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.44043623, 0.2546282 , 0.06702163],
        [0.69403631, 0.39767085, 0.6589676 ]],

       [[0.54505531, 0.22639046, 0.92370457],
        [0.75152889, 0.55103356, 0.93565327]],

       [[0.86994692, 0.68478471, 0.45597379],
        [0.29439941, 0.37659873, 0.91628708]],

       [[0.75596744, 0.89551796, 0.69751414],
        [0.29365886, 0.87737053, 0.63286258]]])

In [75]:
# Random Interger values
np.random.randint(-4,7, size=(3,3))

array([[5, 6, 5],
       [6, 6, 6],
       [4, 6, 5]])

In [82]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [95]:
##### Be careful when copying arrays!!! #####
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)

[100   2   3]






5. Mathematics (:-])

In [16]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [17]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [6]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [20]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [21]:
a ** 2

array([ 1,  4,  9, 16])

In [22]:
# Take the sin (trygonometria), https://numpy.org/doc/stable/reference/routines.math.html
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [23]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [26]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

a * b

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [27]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [28]:
# Find the determinant, https://numpy.org/doc/stable/reference/routines.linalg.html
c = np.identity(3)
np.linalg.det(c)

1.0

In [29]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
np.min(stats, axis=1)

array([1, 4])

In [31]:
np.max(stats)

6

In [35]:
np.sum(stats)

21

In [36]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [38]:
before = stats = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [41]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2,v1]) # v - vertical



array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [42]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2)) # h - horizontal



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [48]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [51]:
# Boolean Masking and Advanced Indexing
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [52]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [54]:
# You can index with a list in NumPY

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [57]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [58]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [60]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])